name: PHP SAST

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare test environment
      run: mkdir -p tests/test-results

  sast-phpcpd:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/phpcpd src


  sast-phpcs:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/phpcs -s --parallel=4 --standard=misc/phpcs.xml --report=junit --report-file=tests/test-results/phpcs.xml --error-severity=1 --warning-severity=8 src/*


  sast-php-cs-fixer:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/php-cs-fixer --config=misc/phpcsfixer.php fix --dry-run --format=junit --no-interaction > tests/test-results/phpcsfixer.xml

  sast-phpmd:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: find src -maxdepth 1 -mindepth 1 -type d | xargs -I{} -P 4 vendor/bin/phpmd {} text misc/phpmd.xml

  sast-phpstan:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/phpstan analyse --configuration misc/phpstan.neon --no-progress

  sast-phpmnd:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/phpmnd src --ignore-numbers=0,1 --no-interaction --non-zero-exit-on-violation --extensions=all

  sast-psalm:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/psalm -c misc/psalm.xml --show-info=false --threads=4

  sast-security-checker:
    runs-on: ubuntu-latest
    needs: "build"
    steps:
    - name: SAST
      run: vendor/bin/security-checker security:check
